### ISSUE TITLE
graphicx package generates 'Undefined control sequence' when used with TeX.

### ISSUE THREAD

**Issue by DavidLFielding** [davidcarlisle/graphics-pln#3]
## Brief outline of the bug

graphicx package now generates an error when run with tex. 

Our authors use the graphicx package in their TeX submissions. These submission now fail to compile after our upgrade to TeX Live 2020.

## Minimal example showing the bug

mwe.tex:

\input graphicx
\end

**Fails under TeX Live 2020:**

/opt_arxiv/arXivTeX/texlive/2020/bin/arch/tex mwe.tex 
This is TeX, Version 3.14159265 (TeX Live 2020) (preloaded format=tex)
(./mwe.tex
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/plain/graphics-pln/graphicx.te
x
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/plain/graphics-pln/miniltx.tex
) (/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/graphicx.sty
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/graphics.sty
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/trig.sty)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics-cfg/graphics.cf
g)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics-def/dvips.def)
! Undefined control sequence.
l.118 \protected
                \def\includegraphics{%
? 

**Succeeds under TeX Live 2016 (our previous version of TL)**

/opt_arxiv/arXivTeX/texlive/2016/bin/arch/tex mwe.tex 
This is TeX, Version 3.14159265 (TeX Live 2016) (preloaded format=tex)
(./mwe.tex
(/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/plain/graphics-pln/graphicx.te
x
(/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/plain/graphics-pln/miniltx.tex
) (/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
(/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cf
g)
(/opt_arxiv/arXivTeX/texlive/2016/texmf-dist/tex/latex/graphics-def/dvips.def))
)) )
No pages of output.
Transcript written on mwe.log.

**Note: The examples provide with graphics-pln also fail in the same way under TL2020.**

/opt_arxiv/arXivTeX/texlive/2020/bin/arch/tex exmplgrf.tex
This is TeX, Version 3.14159265 (TeX Live 2020) (preloaded format=tex)
(./exmplgrf.tex
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/plain/graphics-pln/graphicx.te
x
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/plain/graphics-pln/miniltx.tex
) (/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/graphicx.sty
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/graphics.sty
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/trig.sty)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics-cfg/graphics.cf
g)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics-def/dvips.def)
! Undefined control sequence.
l.118 \protected
                \def\includegraphics{%
? X
No pages of output.
Transcript written on exmplgrf.log.

**## Log file (required) and possibly PDF file**  

cat mwe.log
This is TeX, Version 3.14159265 (TeX Live 2020) (preloaded format=tex 2020.9.8)  29 OCT 2020 20:46
**mwe.tex
(./mwe.tex
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/plain/graphics-pln/graphicx.te
x
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/plain/graphics-pln/miniltx.tex
\@tempcnta=\count26
\@tempcntb=\count27
\@tempdima=\dimen16
\@tempdimb=\dimen17
\@tempdimc=\dimen18
\@tempboxa=\box16
\@tempskipa=\skip18
\@tempskipb=\skip19
\@temptokena=\toks12
^^JDefining generic filename parser.^^J
\leftmarginv=\dimen19
\leftmarginvi=\dimen20
\@ovxx=\dimen21
\@ovyy=\dimen22
\@ovdx=\dimen23
\@ovdy=\dimen24
\@ovro=\dimen25
\@ovri=\dimen26
\@xdim=\dimen27
\@ydim=\dimen28
\@linelen=\dimen29
\@dashdim=\dimen30
\fboxsep=\dimen31
\fboxrule=\dimen32
) (/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/graphicx.sty
graphicx: 2019/11/30 v1.2a Enhanced LaTeX Graphics (DPC,SPQR)

(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty
keyval: 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks13
)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/graphics.sty
graphics: 2019/11/30 v1.4a Standard LaTeX Graphics (DPC,SPQR)

(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics/trig.sty
trig: 2016/01/03 v1.10 sin cos tan (DPC)
)
(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics-cfg/graphics.cf
g
graphics.cfg: 2016/06/04 v1.11 sample graphics configuration
)
graphics: Driver file: dvips.def

(/opt_arxiv/arXivTeX/texlive/2020/texmf-dist/tex/latex/graphics-def/dvips.def
dvips.def: 2017/06/20 v3.1d Graphics/color driver for dvips
)
! Undefined control sequence.
l.118 \protected
                \def\includegraphics{%
? X
No pages of output.

**Comment by davidcarlisle** [comment]
Hmm latex code has used etex extensions (from 1999 or earlier) for over 10 years so it is just by luck that they happened to work in classic tex here, but recent updates to make more commands robust has resulted in `\protected`  being used in more places...

You can use pdftex (for PDF) or etex (for DVI) 

If you really have to use tex not etex for some reason then  you could add `\let\protected\relax` before loading, this works


```
\let\protected\relax
\input graphicx
\includegraphics{example-image.eps}
\bye
```


Can you use etex and pdftex? That would seem to be the best long term solution, I'm a bit wary of adding ` \let\protected\relax` by default (if it is undefined) as it's not really an emulation just avoidance of error. It's safe enough for the graphics package use but I don't know what else is in the document. But I could perhaps be persuaded.....

but adding

```
\ifx\protected\undefined
\let\protected=\relax
\fi
```

 a local graphics.cfg would work if I didn't update miniltx.tex

**Comment by davidcarlisle** [comment]
@DavidLFielding  actually I notice that graphicx.tex already works around the etex `\detokenize` so it's rather inconsistent not to do the same for `\protected`  I'll update (although I think you should use etex rather than tex for production to match  pdftex (and xetex and luatex) and all latex variants that all have etex enabled.

**Comment by davidcarlisle** [comment]
Update pushed to ctan, thanks for the report.
