### ISSUE TITLE
\@backslashchar needed in miniltx?

### ISSUE THREAD

**Issue by kberry** [davidcarlisle/graphics-pln#4]
Hi David ... got this from Daniel Luecking on the eplain list:

It seems a recent color.sty added \@backslashchar, which is not defined in miniltx.tex. This breaks the use of the color package in eplain. Adding its latex definition to miniltx.tex corrects the problem.

Help? Thanks.

**Comment by davidcarlisle** [comment]
ah will fix, sorry about that.
